export interface Country {
    name: string;
    code: string;
    iso: string;
    flag: string;
}

export const COUNTRIES: Country[] = [
    { name: "Afghanistan", code: "+93", iso: "AF", flag: "https://flagcdn.com/af.svg" },
    { name: "Albania", code: "+355", iso: "AL", flag: "https://flagcdn.com/al.svg" },
    { name: "Algeria", code: "+213", iso: "DZ", flag: "https://flagcdn.com/dz.svg" },
    { name: "Andorra", code: "+376", iso: "AD", flag: "https://flagcdn.com/ad.svg" },
    { name: "Angola", code: "+244", iso: "AO", flag: "https://flagcdn.com/ao.svg" },
    { name: "Argentina", code: "+54", iso: "AR", flag: "https://flagcdn.com/ar.svg" },
    { name: "Armenia", code: "+374", iso: "AM", flag: "https://flagcdn.com/am.svg" },
    { name: "Australia", code: "+61", iso: "AU", flag: "https://flagcdn.com/au.svg" },
    { name: "Austria", code: "+43", iso: "AT", flag: "https://flagcdn.com/at.svg" },
    { name: "Azerbaijan", code: "+994", iso: "AZ", flag: "https://flagcdn.com/az.svg" },
    { name: "Bahrain", code: "+973", iso: "BH", flag: "https://flagcdn.com/bh.svg" },
    { name: "Bangladesh", code: "+880", iso: "BD", flag: "https://flagcdn.com/bd.svg" },
    { name: "Belarus", code: "+375", iso: "BY", flag: "https://flagcdn.com/by.svg" },
    { name: "Belgium", code: "+32", iso: "BE", flag: "https://flagcdn.com/be.svg" },
    { name: "Belize", code: "+501", iso: "BZ", flag: "https://flagcdn.com/bz.svg" },
    { name: "Benin", code: "+229", iso: "BJ", flag: "https://flagcdn.com/bj.svg" },
    { name: "Bhutan", code: "+975", iso: "BT", flag: "https://flagcdn.com/bt.svg" },
    { name: "Bolivia", code: "+591", iso: "BO", flag: "https://flagcdn.com/bo.svg" },
    { name: "Bosnia and Herzegovina", code: "+387", iso: "BA", flag: "https://flagcdn.com/ba.svg" },
    { name: "Botswana", code: "+267", iso: "BW", flag: "https://flagcdn.com/bw.svg" },
    { name: "Brazil", code: "+55", iso: "BR", flag: "https://flagcdn.com/br.svg" },
    { name: "Bulgaria", code: "+359", iso: "BG", flag: "https://flagcdn.com/bg.svg" },
    { name: "Cambodia", code: "+855", iso: "KH", flag: "https://flagcdn.com/kh.svg" },
    { name: "Cameroon", code: "+237", iso: "CM", flag: "https://flagcdn.com/cm.svg" },
    { name: "Canada", code: "+1", iso: "CA", flag: "https://flagcdn.com/ca.svg" },
    { name: "Chad", code: "+235", iso: "TD", flag: "https://flagcdn.com/td.svg" },
    { name: "Chile", code: "+56", iso: "CL", flag: "https://flagcdn.com/cl.svg" },
    { name: "China", code: "+86", iso: "CN", flag: "https://flagcdn.com/cn.svg" },
    { name: "Colombia", code: "+57", iso: "CO", flag: "https://flagcdn.com/co.svg" },
    { name: "Costa Rica", code: "+506", iso: "CR", flag: "https://flagcdn.com/cr.svg" },
    { name: "Croatia", code: "+385", iso: "HR", flag: "https://flagcdn.com/hr.svg" },
    { name: "Cuba", code: "+53", iso: "CU", flag: "https://flagcdn.com/cu.svg" },
    { name: "Cyprus", code: "+357", iso: "CY", flag: "https://flagcdn.com/cy.svg" },
    { name: "Czech Republic", code: "+420", iso: "CZ", flag: "https://flagcdn.com/cz.svg" },
    { name: "Denmark", code: "+45", iso: "DK", flag: "https://flagcdn.com/dk.svg" },
    { name: "Djibouti", code: "+253", iso: "DJ", flag: "https://flagcdn.com/dj.svg" },
    { name: "Ecuador", code: "+593", iso: "EC", flag: "https://flagcdn.com/ec.svg" },
    { name: "Egypt", code: "+20", iso: "EG", flag: "https://flagcdn.com/eg.svg" },
    { name: "El Salvador", code: "+503", iso: "SV", flag: "https://flagcdn.com/sv.svg" },
    { name: "Estonia", code: "+372", iso: "EE", flag: "https://flagcdn.com/ee.svg" },
    { name: "Ethiopia", code: "+251", iso: "ET", flag: "https://flagcdn.com/et.svg" },
    { name: "Fiji", code: "+679", iso: "FJ", flag: "https://flagcdn.com/fj.svg" },
    { name: "Finland", code: "+358", iso: "FI", flag: "https://flagcdn.com/fi.svg" },
    { name: "France", code: "+33", iso: "FR", flag: "https://flagcdn.com/fr.svg" },
    { name: "Georgia", code: "+995", iso: "GE", flag: "https://flagcdn.com/ge.svg" },
    { name: "Germany", code: "+49", iso: "DE", flag: "https://flagcdn.com/de.svg" },
    { name: "Ghana", code: "+233", iso: "GH", flag: "https://flagcdn.com/gh.svg" },
    { name: "Greece", code: "+30", iso: "GR", flag: "https://flagcdn.com/gr.svg" },
    { name: "Guatemala", code: "+502", iso: "GT", flag: "https://flagcdn.com/gt.svg" },
    { name: "Guinea", code: "+224", iso: "GN", flag: "https://flagcdn.com/gn.svg" },
    { name: "Haiti", code: "+509", iso: "HT", flag: "https://flagcdn.com/ht.svg" },
    { name: "Honduras", code: "+504", iso: "HN", flag: "https://flagcdn.com/hn.svg" },
    { name: "Hong Kong", code: "+852", iso: "HK", flag: "https://flagcdn.com/hk.svg" },
    { name: "Hungary", code: "+36", iso: "HU", flag: "https://flagcdn.com/hu.svg" },
    { name: "Iceland", code: "+354", iso: "IS", flag: "https://flagcdn.com/is.svg" },
    { name: "India", code: "+91", iso: "IN", flag: "https://flagcdn.com/in.svg" },
    { name: "Indonesia", code: "+62", iso: "ID", flag: "https://flagcdn.com/id.svg" },
    { name: "Iran", code: "+98", iso: "IR", flag: "https://flagcdn.com/ir.svg" },
    { name: "Iraq", code: "+964", iso: "IQ", flag: "https://flagcdn.com/iq.svg" },
    { name: "Ireland", code: "+353", iso: "IE", flag: "https://flagcdn.com/ie.svg" },
    { name: "Israel", code: "+972", iso: "IL", flag: "https://flagcdn.com/il.svg" },
    { name: "Italy", code: "+39", iso: "IT", flag: "https://flagcdn.com/it.svg" },
    { name: "Jamaica", code: "+1", iso: "JM", flag: "https://flagcdn.com/jm.svg" },
    { name: "Japan", code: "+81", iso: "JP", flag: "https://flagcdn.com/jp.svg" },
    { name: "Jordan", code: "+962", iso: "JO", flag: "https://flagcdn.com/jo.svg" },
    { name: "Kazakhstan", code: "+7", iso: "KZ", flag: "https://flagcdn.com/kz.svg" },
    { name: "Kenya", code: "+254", iso: "KE", flag: "https://flagcdn.com/ke.svg" },
    { name: "Kuwait", code: "+965", iso: "KW", flag: "https://flagcdn.com/kw.svg" },
    { name: "Kyrgyzstan", code: "+996", iso: "KG", flag: "https://flagcdn.com/kg.svg" },
    { name: "Laos", code: "+856", iso: "LA", flag: "https://flagcdn.com/la.svg" },
    { name: "Latvia", code: "+371", iso: "LV", flag: "https://flagcdn.com/lv.svg" },
    { name: "Lebanon", code: "+961", iso: "LB", flag: "https://flagcdn.com/lb.svg" },
    { name: "Libya", code: "+218", iso: "LY", flag: "https://flagcdn.com/ly.svg" },
    { name: "Liechtenstein", code: "+423", iso: "LI", flag: "https://flagcdn.com/li.svg" },
    { name: "Lithuania", code: "+370", iso: "LT", flag: "https://flagcdn.com/lt.svg" },
    { name: "Luxembourg", code: "+352", iso: "LU", flag: "https://flagcdn.com/lu.svg" },
    { name: "Macau", code: "+853", iso: "MO", flag: "https://flagcdn.com/mo.svg" },
    { name: "Macedonia", code: "+389", iso: "MK", flag: "https://flagcdn.com/mk.svg" },
    { name: "Madagascar", code: "+261", iso: "MG", flag: "https://flagcdn.com/mg.svg" },
    { name: "Malaysia", code: "+60", iso: "MY", flag: "https://flagcdn.com/my.svg" },
    { name: "Maldives", code: "+960", iso: "MV", flag: "https://flagcdn.com/mv.svg" },
    { name: "Mali", code: "+223", iso: "ML", flag: "https://flagcdn.com/ml.svg" },
    { name: "Malta", code: "+356", iso: "MT", flag: "https://flagcdn.com/mt.svg" },
    { name: "Mexico", code: "+52", iso: "MX", flag: "https://flagcdn.com/mx.svg" },
    { name: "Monaco", code: "+377", iso: "MC", flag: "https://flagcdn.com/mc.svg" },
    { name: "Mongolia", code: "+976", iso: "MN", flag: "https://flagcdn.com/mn.svg" },
    { name: "Montenegro", code: "+382", iso: "ME", flag: "https://flagcdn.com/me.svg" },
    { name: "Morocco", code: "+212", iso: "MA", flag: "https://flagcdn.com/ma.svg" },
    { name: "Mozambique", code: "+258", iso: "MZ", flag: "https://flagcdn.com/mz.svg" },
    { name: "Myanmar", code: "+95", iso: "MM", flag: "https://flagcdn.com/mm.svg" },
    { name: "Namibia", code: "+264", iso: "NA", flag: "https://flagcdn.com/na.svg" },
    { name: "Nepal", code: "+977", iso: "NP", flag: "https://flagcdn.com/np.svg" },
    { name: "Netherlands", code: "+31", iso: "NL", flag: "https://flagcdn.com/nl.svg" },
    { name: "New Zealand", code: "+64", iso: "NZ", flag: "https://flagcdn.com/nz.svg" },
    { name: "Nicaragua", code: "+505", iso: "NI", flag: "https://flagcdn.com/ni.svg" },
    { name: "Nigeria", code: "+234", iso: "NG", flag: "https://flagcdn.com/ng.svg" },
    { name: "North Korea", code: "+850", iso: "KP", flag: "https://flagcdn.com/kp.svg" },
    { name: "Norway", code: "+47", iso: "NO", flag: "https://flagcdn.com/no.svg" },
    { name: "Oman", code: "+968", iso: "OM", flag: "https://flagcdn.com/om.svg" },
    { name: "Pakistan", code: "+92", iso: "PK", flag: "https://flagcdn.com/pk.svg" },
    { name: "Panama", code: "+507", iso: "PA", flag: "https://flagcdn.com/pa.svg" },
    { name: "Paraguay", code: "+595", iso: "PY", flag: "https://flagcdn.com/py.svg" },
    { name: "Peru", code: "+51", iso: "PE", flag: "https://flagcdn.com/pe.svg" },
    { name: "Philippines", code: "+63", iso: "PH", flag: "https://flagcdn.com/ph.svg" },
    { name: "Poland", code: "+48", iso: "PL", flag: "https://flagcdn.com/pl.svg" },
    { name: "Portugal", code: "+351", iso: "PT", flag: "https://flagcdn.com/pt.svg" },
    { name: "Qatar", code: "+974", iso: "QA", flag: "https://flagcdn.com/qa.svg" },
    { name: "Romania", code: "+40", iso: "RO", flag: "https://flagcdn.com/ro.svg" },
    { name: "Russia", code: "+7", iso: "RU", flag: "https://flagcdn.com/ru.svg" },
    { name: "Saudi Arabia", code: "+966", iso: "SA", flag: "https://flagcdn.com/sa.svg" },
    { name: "Serbia", code: "+381", iso: "RS", flag: "https://flagcdn.com/rs.svg" },
    { name: "Singapore", code: "+65", iso: "SG", flag: "https://flagcdn.com/sg.svg" },
    { name: "Slovakia", code: "+421", iso: "SK", flag: "https://flagcdn.com/sk.svg" },
    { name: "Slovenia", code: "+386", iso: "SI", flag: "https://flagcdn.com/si.svg" },
    { name: "South Africa", code: "+27", iso: "ZA", flag: "https://flagcdn.com/za.svg" },
    { name: "South Korea", code: "+82", iso: "KR", flag: "https://flagcdn.com/kr.svg" },
    { name: "Spain", code: "+34", iso: "ES", flag: "https://flagcdn.com/es.svg" },
    { name: "Sri Lanka", code: "+94", iso: "LK", flag: "https://flagcdn.com/lk.svg" },
    { name: "Sudan", code: "+249", iso: "SD", flag: "https://flagcdn.com/sd.svg" },
    { name: "Sweden", code: "+46", iso: "SE", flag: "https://flagcdn.com/se.svg" },
    { name: "Switzerland", code: "+41", iso: "CH", flag: "https://flagcdn.com/ch.svg" },
    { name: "Syria", code: "+963", iso: "SY", flag: "https://flagcdn.com/sy.svg" },
    { name: "Taiwan", code: "+886", iso: "TW", flag: "https://flagcdn.com/tw.svg" },
    { name: "Tajikistan", code: "+992", iso: "TJ", flag: "https://flagcdn.com/tj.svg" },
    { name: "Thailand", code: "+66", iso: "TH", flag: "https://flagcdn.com/th.svg" },
    { name: "Tunisia", code: "+216", iso: "TN", flag: "https://flagcdn.com/tn.svg" },
    { name: "Turkey", code: "+90", iso: "TR", flag: "https://flagcdn.com/tr.svg" },
    { name: "Turkmenistan", code: "+993", iso: "TM", flag: "https://flagcdn.com/tm.svg" },
    { name: "Uganda", code: "+256", iso: "UG", flag: "https://flagcdn.com/ug.svg" },
    { name: "Ukraine", code: "+380", iso: "UA", flag: "https://flagcdn.com/ua.svg" },
    { name: "UAE", code: "+971", iso: "AE", flag: "https://flagcdn.com/ae.svg" },
    { name: "United Kingdom", code: "+44", iso: "GB", flag: "https://flagcdn.com/gb.svg" },
    { name: "United States", code: "+1", iso: "US", flag: "https://flagcdn.com/us.svg" },
    { name: "Uruguay", code: "+598", iso: "UY", flag: "https://flagcdn.com/uy.svg" },
    { name: "Uzbekistan", code: "+998", iso: "UZ", flag: "https://flagcdn.com/uz.svg" },
    { name: "Venezuela", code: "+58", iso: "VE", flag: "https://flagcdn.com/ve.svg" },
    { name: "Vietnam", code: "+84", iso: "VN", flag: "https://flagcdn.com/vn.svg" },
    { name: "Yemen", code: "+967", iso: "YE", flag: "https://flagcdn.com/ye.svg" },
    { name: "Zimbabwe", code: "+263", iso: "ZW", flag: "https://flagcdn.com/zw.svg" }
].sort((a, b) => a.name.localeCompare(b.name));

export const getCountryByIso = (iso: string) => COUNTRIES.find(c => c.iso === iso) || COUNTRIES[0];
